name: Trigger Katalon Tests

on:
  push: 
    branches : [main]

jobs:
  trriger:
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch Event to Katalon Repo
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          repository: hyoni91/ticket-booking-automation
          event-type: trigger-tests
